### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by TristanMrb** [Multiflexxx/server-flex-rent#1]
## ER-Modell

| Entity | Missing Attributes |
| ------------- |-------------|
| user | <ul><li>birthday</li><li>identity verification</li><li>member since</li></ul> |
| offer | <ul><li>description</li><li>offer rating</li></ul> |

Check for other missing attributes!

**Comment by NerdyStuff** [comment]
should be done in commit fcab9b15a96093001ca95815cedae3b8a870df7e
