### ISSUE TITLE
Check HTTP response codes

### ISSUE THREAD

**Issue by Grimmig18** [Multiflexxx/server-flex-rent#38]
Some HTTP response codes are wrong by default: e.g.: `POST` on `/user` returns `201`

**Comment by NerdyStuff** [comment]
Check this out: https://medium.com/@petertboyer/learn-restful-api-design-ideals-c5ec915a430f

**Comment by NerdyStuff** [comment]
And this: https://docs.nestjs.com/exception-filters

**Comment by aalenaa** [comment]
doesn't matter

**Comment by NerdyStuff** [comment]
Wont do it
