### ISSUE TITLE
Create in App chat functionality

### ISSUE THREAD

**Issue by NerdyStuff** [Multiflexxx/server-flex-rent#7]
Create Tables in Database for in app communication.
Create also a concept for chat.

**Comment by Grimmig18** [comment]
1. Create Public / Private Key Pair for user
2. Safe Public key on server, private key only on user's device
3. When adding a secondary device.
- Generate secure (symmetric) key and display as QR code on secondary device
- Scan QR code on primary device
- Use sym. key to encrypt private key and send to server
- on secondary device: get encrypted private key from server and encrypt using sym. key
4. Sync messages <be>

This needs to be done once for every added device, and every time when using a web-browser to send messages. <br>
**Question**: How to safe Messages?
**Answer**: Locally. When a new message is sent to a user, create a new message on our server. The client then asks the server for new messages, when coming back online. The server then responds with a collection of new messages, which the client can decrypt using the local private key. After receiving the messages, the clients sends another request to the server, telling the server they received messages (by message_id). The server then can delete the queued messages. <br>
**Consider**: what to do with multiple devices? <br>
**Suggestion**: Keep a list of devices associated with a single user and only delete the messages from the queue for a single device at a time. (Or maybe keep messages for a certain amount of time?)

**Comment by NerdyStuff** [comment]
Done
